import React from "react";
import { useNavigate } from "react-router-dom";
import Logo from "../components/common/Logo";

const features = [["Practice with purpose", "Curated Codeforces-style problems, sorted by level."], ["Host friend contests", "Create a private room, invite friends, and start when everyone is ready."], ["Track the climb", "See solved problems and submissions as you improve."]];

export default function LandingPage() {
  const navigate = useNavigate();
  return <main className="min-h-screen bg-slate-950 text-white"><nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><Logo size="md" /><div className="flex gap-3"><button onClick={() => navigate("/login")} className="rounded-lg px-4 py-2 text-sm font-semibold text-slate-200 hover:bg-white/10">Log in</button><button onClick={() => navigate("/signup")} className="rounded-lg bg-indigo-500 px-4 py-2 text-sm font-semibold hover:bg-indigo-400">Start competing</button></div></nav><section className="mx-auto max-w-4xl px-6 pb-24 pt-20 text-center"><p className="inline-block rounded-full border border-indigo-400/30 bg-indigo-400/10 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-indigo-300">Coding contests for your crew</p><h1 className="mt-7 text-5xl font-black leading-tight tracking-tight sm:text-7xl">Practice harder.<br /><span className="text-indigo-400">Compete together.</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-300">A focused space to solve programming problems, run Codeforces-style contests, and chase the leaderboard with friends.</p><div className="mt-9 flex justify-center gap-3"><button onClick={() => navigate("/signup")} className="rounded-xl bg-indigo-500 px-6 py-3 font-bold hover:bg-indigo-400">Create your account →</button><button onClick={() => navigate("/login")} className="rounded-xl border border-white/20 px-6 py-3 font-bold hover:bg-white/10">Enter a contest</button></div></section><section className="mx-auto grid max-w-6xl gap-4 px-6 pb-20 md:grid-cols-3">{features.map(([title, text], index) => <article key={title} className="rounded-2xl border border-white/10 bg-white/5 p-6"><span className="text-2xl">{["⌘", "⚔", "↗"][index]}</span><h2 className="mt-5 text-lg font-bold">{title}</h2><p className="mt-2 leading-6 text-slate-400">{text}</p></article>)}</section></main>;
}
